# fly.toml — конфиг для Telegram Gifts Profit Bot
app = "telegram-gifts-profit-bot" 
primary_region = "fra"

[build]
  builder = "heroku/builder:24"

[env]
  NODE_ENV = "production"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
  cpu_kind = "shared"

[processes]
  app = "npm start"
